import React,{useEffect,useMemo,useState}from'react';import{createRoot}from'react-dom/client';import{Search,MapPin,RefreshCw,Trophy,CheckCircle2}from'lucide-react';import{parseSpreadsheetSheets}from'./uploadParser.js';import'./style.css';
const STORE_NAMES=["Sam's Club","Walmart","Albertsons","Safeway","Smith's"];
const positive=n=>typeof n==='number'&&Number.isFinite(n)&&n>0?n:null;
const money=n=>positive(n)?'$'+Number(n).toFixed(2):null;
const displayPrice=o=>positive(o?.promo_price)||positive(o?.price);
const sourceLabel=o=>o?.source?.collector==='browser-run'?'Browser':o?.source?.file?'XLSX':(o?.source?.collector||o?.source?.source||'Price');
function Uploader({onSaved}){const[open,setOpen]=useState(false),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[status,setStatus]=useState('');async function upload(ev){const files=[...ev.target.files];if(!files.length)return;setBusy(true);setStatus('Reading spreadsheet…');try{const XLSX=await import('xlsx');const messages=[];for(const file of files){if(file.size>5242880)throw Error(file.name+': maximum file size is 5 MB.');const bytes=await file.arrayBuffer();const book=XLSX.read(bytes,{type:'array'});const parsed=parseSpreadsheetSheets(book.SheetNames.map(name=>({name,values:XLSX.utils.sheet_to_json(book.Sheets[name],{header:1,defval:null,blankrows:true})})),file.name);if(!parsed.usable_rows){messages.push(file.name+': no supported priced products found — skipped');setStatus(messages.join(' • '));continue;}const digest=await crypto.subtle.digest('SHA-256',bytes);const hash=[...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,'0')).join('');const res=await fetch('/api/uploads',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+password},body:JSON.stringify({...parsed,hash})});const body=await res.json();if(!res.ok)throw Error(body.error||'Upload failed.');messages.push(file.name+': '+(body.duplicate?'already imported':body.usable_rows+' rows saved, '+body.excluded_rows+' excluded'));setStatus(messages.join(' • '));await onSaved();}}catch(e){setStatus(e.message||'Upload failed.')}finally{setBusy(false);ev.target.value='';}}return <section className="upload"><button className="uploadButton" onClick={()=>setOpen(!open)} aria-expanded={open}>Upload spreadsheets</button><span> Walmart · Smith's · Sam's Club · Albertsons · Safeway</span>{open&&<div className="uploadForm"><label>Upload password <input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label><label className="fileLabel">Choose .xlsx files <input aria-label="Choose spreadsheets" type="file" accept=".xlsx,.xls" multiple disabled={busy||!password} onChange={upload}/></label></div>}<p role="status" aria-live="polite">{status}</p></section>}
function App(){
 const[legacy,setLegacy]=useState(null),[catalog,setCatalog]=useState({products:[],groups:[],category_order:[]}),[q,setQ]=useState(''),[cat,setCat]=useState('All'),[err,setErr]=useState('');
 const loadCatalog=()=>fetch('/api/catalog?refresh='+Date.now(),{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('Catalog unavailable');return r.json()}).then(x=>{setCatalog(x);return x}).catch(e=>{setErr(e.message);return null});
 useEffect(()=>{loadCatalog();fetch('/data/prices.json?refresh='+Date.now(),{cache:'no-store'}).then(r=>r.ok?r.json():null).then(setLegacy).catch(()=>null)},[]);
 const products=catalog.products||[],groups=catalog.groups||[];
 const cats=['All',...(catalog.category_order||[])];
 const shown=useMemo(()=>groups.filter(g=>(cat==='All'||g.category===cat)&&((g.name||'')+' '+g.products.map(p=>p.name).join(' ')).toLowerCase().includes(q.toLowerCase())),[groups,cat,q]);
 const priceCount=products.filter(p=>p.observations?.length).length;
 const latest=p=>{const a=(p?.observations||[]).filter(o=>displayPrice(o)||positive(o?.unit_price));return a[a.length-1]||null;};
 return <><header><div className="brand">🛒 <span>Farmington Grocery Watch</span></div><div className="location"><MapPin size={15}/> Farmington, NM</div><div className="updated"><RefreshCw size={13}/> LIVE CATALOG</div></header><main>
 <Uploader onSaved={loadCatalog}/>
 <section className="miniStats"><div><b>{products.length}</b><span>foods tracked</span></div><div><b>{priceCount}</b><span>priced products</span></div><div><b>{catalog.batches||0}</b><span>spreadsheet batches</span></div></section>
 <section className="controls"><div className="search"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search groceries..."/></div><div className="cats">{cats.map(x=><button key={x} className={cat===x?'active':''} onClick={()=>setCat(x)}>{x}</button>)}</div></section>
 <section className="panel"><div className="panelhead"><div><h2>Grocery price comparison</h2><p>Every imported retailer product is kept. Equivalent products are grouped across stores; variants stay separate.</p></div><span>{shown.length} groups · {products.length} products</span></div>
 {err&&products.length===0?<div className="error">{err}</div>:<div className="scroll"><table><thead><tr><th>Item</th>{STORE_NAMES.map(x=><th key={x}>{x}</th>)}<th>Best</th></tr></thead><tbody>
 {shown.map(g=>{const cells=STORE_NAMES.map(store=>{const p=g.stores?.[store];const o=latest(p);return{p,o}});let best=-1,bestVal=Infinity;cells.forEach((c,i)=>{const v=positive(c.o?.unit_price)||displayPrice(c.o);if(v&&v<bestVal){bestVal=v;best=i}});return <tr key={g.id}><td><b>{g.name}</b><small>{g.category}{g.variant?.lean?' · '+g.variant.lean:''}{g.variant?.size?' · '+g.variant.size:''}</small></td>{cells.map((c,i)=><td key={STORE_NAMES[i]} className={c.o?(i===best?'priceCell best':'priceCell'):''}>{c.o?<><strong>{money(displayPrice(c.o))||'—'}</strong>{c.o.regular_price&&c.o.promo_price?<small>was {money(c.o.regular_price)}</small>:null}<small>{c.o.unit_price?money(c.o.unit_price)+'/'+(c.o.unit||'unit'):c.p?.package||''}</small><em title={c.o.source?.source_url||''}><CheckCircle2 size={10}/> {sourceLabel(c.o)}</em></>:<span className="missing">—</span>}</td>)}<td className="winner">{best>=0?<><Trophy size={12}/> {STORE_NAMES[best]}</>:'—'}</td></tr>})}
 </tbody></table></div>}</section>
 <div className="freshness">Catalog source: <b>retailer spreadsheets + automated collectors</b>{legacy?.meta?.updated_at?' · legacy history retained':''}</div>
 </main></>
}
createRoot(document.getElementById('root')).render(<App/>);+Number(n).toFixed(2):null;const displayPrice=o=>positive(o?.promo_price)||positive(o?.price);const sourceLabel=o=>o?.source?.collector==='browser-run'?'Browser':o?.source?.file?'XLSX':(o?.source?.collector||o?.source?.source||'Price');
